/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2016-2020 hyStrath
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of hyStrath, a derivative work of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    standardCyclic

Description


SourceFiles
    standardCyclic.C


\*---------------------------------------------------------------------------*/

#ifndef standardCyclic_H
#define standardCyclic_H

#include "cyclicBoundary.H"


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class standardCyclic Declaration
\*---------------------------------------------------------------------------*/

class standardCyclic
:
	public cyclicBoundary
{

private:

    // Private data
        dictionary propsDict_;



public:

    //- Runtime type information
    TypeName("standardCyclic");

    // Constructors

        //- Construct from components
        standardCyclic
		(
            Time& t,
            const polyMesh& mesh,
            const dictionary& dict
		);

    // Destructor

 		~standardCyclic();


    // Member Functions



        // Access


};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
