#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

cases="pressureCoeff frictionCoeff2T StantonNumber yPlus2T"

for case in $cases
do
  cd $case
  wmake $targetType
  cd ../
done
