#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ./constant/backup-polyMesh ./constant/polyMesh
runApplication checkMesh

runApplication hy2Foam

hy2Foam -postProcess -dict 'system/surfaceCoefficients' -latestTime

