#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f log.postProcess
runApplication postProcess -func singleGraph -latestTime

timeFolders=`ls -d [0-9]*`
timeFolder=`echo $timeFolders | rev | cut -d ' ' -f1 | rev`

resultFolders=`ls -d postProcessing/singleGraph/[0-9]*`
resultFolder="postProcessing/singleGraph/$timeFolder"

for resultFolder in $resultFolders; do
  paste $resultFolder/line_UMean_mixture.xy $resultFolder/line_rhoN_N2_rhoN_O2_rotationalT_mixture_translationalT_mixture_vibrationalT_N2_vibrationalT_O2.xy > $resultFolder/line_UMean_mixture_rhoN_N2_rhoN_O2_rotationalT_mixture_translationalT_mixture_vibrationalT_N2_vibrationalT_O2.xy
  awk '{$3=$4=$5=""; print $0}' $resultFolder/line_UMean_mixture_rhoN_N2_rhoN_O2_rotationalT_mixture_translationalT_mixture_vibrationalT_N2_vibrationalT_O2.xy > $resultFolder/line_UxMix_rhoNN2_rhoNO2_TrMix_TtMix_TvN2_TvO2.xy
  awk '{ print $1 " " $2 " " 0.4*$5+0.6*$6 " " $7 " " $8 " " $3 " " $4}' $resultFolder/line_UxMix_rhoNN2_rhoNO2_TrMix_TtMix_TvN2_TvO2.xy > $resultFolder/line_UxMix_TtrMix_TvN2_TvO2_rhoNN2_rhoNO2.xy
  rm -f $resultFolder/line_UMean_mixture.xy $resultFolder/line_rhoN_N2_rhoN_O2_rotationalT_mixture_translationalT_mixture_vibrationalT_N2_vibrationalT_O2.xy $resultFolder/line_UMean_mixture_rhoN_N2_rhoN_O2_rotationalT_mixture_translationalT_mixture_vibrationalT_N2_vibrationalT_O2.xy $resultFolder/line_UxMix_rhoNN2_rhoNO2_TrMix_TtMix_TvN2_TvO2.xy
done
