#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication gmshToFoam ./constant/backup-polyMesh/bluntedCone.msh
cp constant/backup-polyMesh/backup-boundary constant/polyMesh/boundary
runApplication checkMesh

runApplication hy2Foam

runApplication postProcess -func singleGraph -latestTime


