#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

currentDir=`pwd`

read -r -p "Please confirm? [Y/n] " input
 
case $input in
    [yY][eE][sS]|[yY])
       # For all the sub-directories containing a 'Allclean' file
       for dir in `find . \( -type f -a -name Allclean \)`
       do
           dir=${dir%/Allclean}
           echo $dir
           if [ -e "$dir/Allclean" ]
           then
               cd $dir
               ./Allclean > /dev/null 2>&1 
               cd $currentDir
           fi
       done
       echo "Cleaned"
       ;;
    [nN][oO]|[nN])
       echo "Aborted"
       ;;
    *)
 echo "Invalid input"
 exit 1
 ;;
esac
