#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType VTRelaxationModels
wmake $makeType VVRelaxationModels
wmake $makeType eVRelaxationModels
wmake $makeType relaxationTimeModels


# ----------------------------------------------------------------- end-of-file
