#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wclean $makeType VTRelaxationModels
wclean $makeType VVRelaxationModels
wclean $makeType eVRelaxationModels
wclean $makeType relaxationTimeModels

# ----------------------------------------------------------------- end-of-file
