#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

nProcs=1
if [ $# -ne 0 ]
  then nProcs=$1;
fi

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication createPatch -overwrite

postProcess -func writeCellCentres -time '0' > /dev/null 2>&1
gcc calculateBMSL.C -o calculateB_MSL -lm
./calculateB_MSL > /dev/null 2>&1
rm 0/C 0/Cx 0/Cy 0/Cz

cp -r backup_NR_0.0014 0.0014
mv 0/B 0.0014/

if [ $nProcs -eq 1 ] ; then
  runApplication hy2MhdFoam
else
  runApplication decomposePar -latestTime
  mpirun -np $nProcs hy2MhdFoam -parallel > log.hy2MhdFoam 2>&1
  runApplication reconstructPar -latestTime
fi
