#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ./constant/backup-polyMesh ./constant/polyMesh
cp -r ./backup-0.00127 ./0.00127

runApplication checkMesh

hy2Foam > log.hyFoam

