#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial mesh functions
fluentMeshToFoam system/fireII.msh
makeAxialMesh -axis AXIS -wedge frontAndBackPlanes -wedgeAngle 4
cp 1e-10/polyMesh/* constant/polyMesh/
rm -r 1e-10/
collapseEdges
cp 1e-10/polyMesh/* constant/polyMesh/
rm -r 1e-10/

# REMOVE PATCHES with 0 FACES in constant/polyMesh/boundary
# EDIT NUMBER of patches in constant/polyMesh/boundary
# EDIT PATCHES NAMES in constant/polyMesh/boundary
cp system/backup-boundary constant/polyMesh/boundary
