#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

nProcs=1
if [ $# -ne 0 ]
  then nProcs=$1;
fi

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication dsmcInitialise+

if [ $nProcs -eq 1 ]
  then runApplication dsmcFoam+
else
  runApplication decomposePar -latestTime
  runApplication mpirun -np $nProcs dsmcFoam+ -parallel
  runApplication reconstructPar -latestTime
fi  

