/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2007 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Class
    dsmcInitialiseOnLine

Description


SourceFiles
    dsmcInitialiseOnLineI.H
    dsmcInitialiseOnLine.C
    dsmcInitialiseOnLineIO.C


\*---------------------------------------------------------------------------*/

#ifndef dsmcInitialiseOnLine_H
#define dsmcInitialiseOnLine_H

#include "dsmcAllConfigurations.H"
#include "vector.H"
#include "polyMesh.H"
#include "volFields.H"
#include "dsmcCloud.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class dsmcInitialiseOnLine Declaration
\*---------------------------------------------------------------------------*/

class dsmcInitialiseOnLine
:
	public dsmcConfiguration
{

private:

    // Private data

        //- subDictionary containing the properties
//         dictionary propsDict_;

    vector startPosition_;
    vector endPosition_;


    // Private Member Functions




public:

    //- Runtime type information
    TypeName("dsmcInitialiseOnLine");

    // Constructors

        //- Construct from components
        dsmcInitialiseOnLine
		(
            dsmcCloud& cloud,
            const dictionary& dict
		);

    // Destructor

 		~dsmcInitialiseOnLine();


    // Member Functions

        void setInitialConfiguration();

};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
