#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType general
wmake $makeType potential
wmake $makeType molecularMeasurements
wmake $makeType molecule
wmake $makeType polyCloud

# ----------------------------------------------------------------- end-of-file
