#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ./constant/backup-polyMesh ./constant/polyMesh
runApplication checkMesh

cp -r ./backup-0.015 ./0.015

hy2Foam > log.hyFoam

runApplication pressureCoeff -latestTime
