#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
sed -i -e 's/empty/wall/g' constant/polyMesh/boundary
runApplication dsmcInitialise+
runApplication dsmcFoam+ &

# ----------------------------------------------------------------- end-of-file
