#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
cleanType=${1:-libso}
set -x

wclean $cleanType strathSpecie

wclean $cleanType strathReactionThermo
wclean $cleanType strathChemistryModel

strathSpecie/relaxationTimes/Allwclean $*
strathSpecie/transport/speciesDiffusion/Allwclean $*
wclean $cleanType strathSpecie/transport/mixingRules
strathSpecie/rarefied/Allwclean $*

find . -name "*~" -delete

# ----------------------------------------------------------------- end-of-file
