#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

./strathSpecie/relaxationTimes/Allwmake $*
./strathSpecie/transport/speciesDiffusion/Allwmake $*
wmake $makeType ./strathSpecie/transport/mixingRules
./strathSpecie/rarefied/Allwmake $*

# ----------------------------------------------------------------- end-of-file
