#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType ./strathSpecie
wmake $makeType ./strathReactionThermo
wmake $makeType ./strathChemistryModel

# ----------------------------------------------------------------- end-of-file
