/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2005 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Class


Description

SourceFiles


\*---------------------------------------------------------------------------*/

#ifndef rdf_H
#define rdf_H

#include "IFstream.H"
#include "OFstream.H"
#include "radialDistribution.H"
#include "rdfModel.H"
#include "Time.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class rdf Declaration
\*---------------------------------------------------------------------------*/

class rdf
{
    // Private data

        radialDistribution rdfDistr_;

        autoPtr<rdfModel> rdfModel_;
        
        Time& time_;

    // Private Member Functions

public:

    // Constructors

        //- Construct from dictionary
        rdf(const dictionary& dict, Time& t);
    // Destructor

        ~rdf();

    // Member Functions


        // Access

            const radialDistribution& RDF() const;

        // Check

        // Edit

        // Write

            void write();

    // Member Operators

//         void operator=(const rdf&);

    // Friend Functions

    // Friend Operators

    // IOstream Operators
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
