#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wclean $makeType turbulenceModel
wclean $makeType RAS

rmdepall

# ----------------------------------------------------------------- end-of-file
