#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanSamples

rm~all
rm -rf 0 boundaries fieldMeasurements > /dev/null
