#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication checkMesh

hy2Foam > log.hyFoamLTS

runApplication postProcess -func singleGraph -latestTime
