/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2007 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Description

\*---------------------------------------------------------------------------*/

#include "polyMesh.H"

namespace Foam
{






// // Construct as copy
// inline pointInfoList::pointInfoList(const pointInfoList& wpt)
// :
//     originPoint_(wpt.originPoint()),
//     currentPoint_(wpt.currentPoint()),
//     currentPointLabel_(wpt.currentPointLabel()),
//     Rsqr_(wpt.Rsqr()),
// //     visitedPoint_(wpt.visitedPoint()),
//     zonePoint_(wpt.isZonePoint()),
//     acceptedPoint_(wpt.isAcceptedPoint()),
//     boundaryPoint_(wpt.isBoundaryPoint()),
//     interfacePoint_(wpt.isInterfacePoint())
// {}


// * * * * * * * * * * * * * Private Member Functions  * * * * * * * * * * * //



// * * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * //








// - Set


// - Access



// * * * * * * * * * * * * * * * Member Operators  * * * * * * * * * * * * * //



} // End namespace Foam

// ************************************************************************* //
