/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2007 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Class
    dsmcFixedHeatFluxWallPatch

Description
    Wall interaction setting microscopic velocity to a random one
    drawn from a Maxwellian distribution corresponding to a specified
    temperature

    SINGLE VALUE: temperature and velocity required in boundariesDict


SourceFiles
    dsmcFixedHeatFluxWallPatch.C


\*---------------------------------------------------------------------------*/

#ifndef dsmcFixedHeatFluxWallPatch_H
#define dsmcFixedHeatFluxWallPatch_H

#include "dsmcPatchBoundary.H"
#include "vector.H"
#include "polyMesh.H"
#include "volFields.H"
#include "dsmcCloud.H"
#include "distribution.H"
#include "timeDataMeas.H"


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class dsmcFixedHeatFluxWallPatch Declaration
\*---------------------------------------------------------------------------*/

class dsmcFixedHeatFluxWallPatch
:
    public dsmcPatchBoundary
{

private:

    // Private data
        dictionary propsDict_;

        volScalarField wallTemperature_;

        scalar EcTot_;
        
        scalar EcTotSum_;
        
        scalar newWallTemperature_;
        
        scalar desiredHeatFlux_;

        scalar relaxationFactor_;

        label stepCounter_;
        
        label nSamples_;
        
        scalar referenceCp_;
        
        scalar referenceRho_;
        
        scalar referenceU_;
        
        scalar referenceTemperature_;

        void setProperties();
        
        void initialTemperatureEstimate();

public:

    //- Runtime type information
    TypeName("dsmcFixedHeatFluxWallPatch");

    // Constructors

        //- Construct from components
        dsmcFixedHeatFluxWallPatch
        (
            Time& t,
            const polyMesh& mesh,
            dsmcCloud& cloud,
            const dictionary& dict
        );

    // Destructor

        ~dsmcFixedHeatFluxWallPatch();


    // Member Functions

        void initialConfiguration();

        //- calculate any required properties
        void calculateProperties();

        //- control the mols
        void controlParticle(dsmcParcel& p, dsmcParcel::trackingData& td);

        //- output data
        void output
        (
            const fileName& fixedPathName,
            const fileName& timePath
        );

        //- update properties from a modified dictionary
        void updateProperties(const dictionary&);



        // Access





};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
